from enum import Enum, auto


class TokenType(Enum):
    MODULE = auto()
    ENDMODULE = auto()
    INPUT = auto()
    OUTPUT = auto()
    WIRE = auto()
    ASSIGN = auto()
    KW_AND = auto()
    KW_OR = auto()
    KW_NOT = auto()
    KW_XOR = auto()
    KW_NAND = auto()
    KW_NOR = auto()
    LOGICAL_AND = auto()
    LOGICAL_OR = auto()
    BIT_AND = auto()
    BIT_OR = auto()
    BIT_NOT = auto()
    BIT_XOR = auto()
    EQUALS = auto()
    LPAREN = auto()
    RPAREN = auto()
    SEMICOLON = auto()
    COMMA = auto()
    IDENTIFIER = auto()
    NUMBER = auto()
    EOF = auto()
