export const TokenType = {
  MODULE: "MODULE",
  ENDMODULE: "ENDMODULE",
  INPUT: "INPUT",
  OUTPUT: "OUTPUT",
  WIRE: "WIRE",
  ASSIGN: "ASSIGN",
  KW_AND: "KW_AND",
  KW_OR: "KW_OR",
  KW_NOT: "KW_NOT",
  KW_XOR: "KW_XOR",
  KW_NAND: "KW_NAND",
  KW_NOR: "KW_NOR",
  LOGICAL_AND: "LOGICAL_AND",
  LOGICAL_OR: "LOGICAL_OR",
  BIT_AND: "BIT_AND",
  BIT_OR: "BIT_OR",
  BIT_NOT: "BIT_NOT",
  BIT_XOR: "BIT_XOR",
  EQUALS: "EQUALS",
  LPAREN: "LPAREN",
  RPAREN: "RPAREN",
  SEMICOLON: "SEMICOLON",
  COMMA: "COMMA",
  IDENTIFIER: "IDENTIFIER",
  NUMBER: "NUMBER",
  EOF: "EOF",
} as const;

export type TokenType = (typeof TokenType)[keyof typeof TokenType];
